services:
  app:
    build: .
    container_name: api_encuestas
    restart: always
    ports:
      - "9501:3001"
    environment:
      - DB_HOST=localhost
      - DB_NAME=encuestas
      - DB_USER=innovacion
      - DB_PASSWORD=innovacion123
      - JWT_SECRET=1nn4v1c34nd3g3t1l
    working_dir: /usr/src/app
    command: npm run dev
